#!/bin/bash

# this probably no longer works as intended due to multidrive setup,
# and honestly, I haven't used the feature much at all, though leaving it up
# for future reference

# help check
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "Usage: "archivejob" [job name] "
  exit 0
fi

# Set default directory, this will not function if using symlinks to call scripts
SCRIPTDIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

# Source config settings, point this at your config.sh file
source $SCRIPTDIR/config_bash

# if error on source config
if [ $? -eq 0 ]; then
    # echo "Config.sh loaded"
    :
else
    echo -e "\n-----CONFIG ERROR-----\nCannot find config.sh doublecheck the filepath \nand/or check config.sh for any typos"
    exit 0
fi

JOB=${1?Error: no job name given}
JPATH=$PROJPATH/$JOB
APATH=$ARCHPATH
OPATH=$ARCHPATH/$JOB

# make new dir
[[ -d "$APATH" ]] || mkdir -p "$APATH"
mv "$JPATH" "$APATH"
echo "Job archived from $JPATH to $OPATH"

# make symlink
ln -s "$OPATH" "${JPATH%/}"
echo "symlink created at $JPATH pointing at $OPATH"
