#!/bin/bash

# help check
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo -e "Usage: jobcreate [new job name]\n\n--Additional arguments--\nCreate job in alternative drive: \n\tcreatejob [new job name] -alt "
  exit 0
fi

# Set default directory, this will not function if using symlinks to call scripts
SCRIPTDIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

# Source config settings, point this at your config.sh file
source $SCRIPTDIR/config_bash

# if error on source config
if [ $? -eq 0 ]; then
    # echo "Config.sh loaded"
    :
else
    echo -e "\n-----CONFIG ERROR-----\nCannot find config.sh doublecheck the filepath \nand/or check config.sh for any typos"
    exit 0
fi

if [ "$2" == "-alt" ]; then
  PROJPATH=$PROJPATH2
fi

JOB=${1?Error: no job name given}
JPATH=$PROJPATH/$JOB
if cd $JPATH; then
	echo "Error: job already exists"
	exit 1
else
	echo "No matching job found, creating new job"
	mkdir $JPATH
fi
