#!/bin/bash

# help check
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo -e "Usage: shotcreate [existing job] [new shot name]\n\n--Additional arguments--\nCreate shot in alternative drive: \n\tshotcreate [existing job] [new shot name] -alt"
  exit 0
fi

# Set default directory, this will not function if using symlinks to call scripts
SCRIPTDIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

# Source config settings, point this at your config.sh file
source $SCRIPTDIR/config_bash

# if error on source config
if [ $? -eq 0 ]; then
    # echo "Config.sh loaded"
    :
else
    echo -e "\n-----CONFIG ERROR-----\nCannot find config.sh doublecheck the filepath \nand/or check config.sh for any typos"
    exit 0
fi

# A lot of optionals here just go through and edit for what you need.
# For example there are a lot of directories related to Nuke/Resolve or
# other more specific directories such as hip/log.

if [ "$3" == "-alt" ]; then
  PROJPATH=$PROJPATH2
fi

JOB=${1?Error: no job name given}
SHOT=${2?Error: no shot name given}
JPATH=$PROJPATH/$JOB
SPATH=$JPATH/$SHOT
if cd $JPATH; then
	if cd $SPATH; then
		echo "Error: shot already exists"
		exit 1
	else
		echo "No matching shot found, creating new shot"
		mkdir $SPATH
		HPATH=$SPATH/houdini
		NPATH=$SPATH/nuke
    RPATH=$SPATH/resolve
    SBPATH=$SPATH/substance
		mkdir $HPATH $HPATH/hip $HPATH/hip/backup $HPATH/hip/log $HPATH/geo $HPATH/renders $HPATH/texture $HPATH/flipbook $HPATH/assets $HPATH/texture/hdri $HPATH/ifd $HPATH/library
		mkdir $NPATH $NPATH/scene $NPATH/scene/backup $NPATH/renders
    mkdir $RPATH $RPATH/backup
    mkdir $SBPATH $SBPATH/spp $SBPATH/exports
  fi
else
	echo "Error: Job name not found, if needed run jobcreate to create a job" 1>&2
	exit 1
fi
